export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'
// export const GET_ARTICLE_DETAIL_PRE = 'GET_ARTICLE_DETAIL_PRE'
// export const GET_ARTICLE_DETAIL_NEXT = 'GET_ARTICLE_DETAIL_NEXT'

