export const INIT_PODCASTER_DASHBOARD = 'INIT_PODCASTER_DASHBOARD';
export const INIT_PODCASTER_AUDIO_LIST = 'INIT_PODCASTER_AUDIO_LIST';
export const ADD_PODCASTER_AUDIO = 'ADD_PODCASTER_AUDIO';
export const INIT_EXPLORE_HOMEPAGE = 'INIT_EXPLORE_HOMEPAGE';
export const INIT_EXPLORE_CATEPAGE = 'INIT_EXPLORE_CATEPAGE';
export const INIT_CHANNEL_PAGE_DATA = 'INIT_CHANNEL_PAGE_DATA';
export const INIT_RATE_MODAL = 'INIT_RATE_MODAL';
