export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL';
export const GET_ARTICLE_DETAIL_PRE = 'GET_ARTICLE_DETAIL_PRE';
export const GET_ARTICLE_DETAIL_NEXT = 'GET_ARTICLE_DETAIL_NEXT';

//samps
export const INIT_MEMBER = 'INIT_MEMBER';
export const LOG_OUT = 'LOG_OUT';
